name: Bug report
title: '[Bug][Module Name] Bug title'
description: Problems and issues with code of Rocket.Chat.Electron
labels: ['type/bug']
body:
  - type: markdown
    attributes:
      value: >
        - Please make sure what you are reporting is indeed a bug with reproducible steps

        - If you want to ask questions or share ideas, you can,
          -  Head to our [Forums](https://forums.rocket.chat) Page
          - [Join our Open Server]( https://open.rocket.chat/channel/support) and send your question

        For better global communication, please write in English.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the existing [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue)
        first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found
            no similar issues.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Please provide the context in which the problem occurred and explain what happened

        1. What operating system and which version?
        2. Which version of Rocket.Chat ([Server](https://github.com/RocketChat/Rocket.Chat/releases))?
            - You could check your Rocket.Chat server's version by going to `<your server>/api/info`, e.g. [http://localhost:3000/api/info](http://localhost:3000/api/info)
        3. Which version of Rocket.Chat.Electron ([Electron/Desktop](https://github.com/RocketChat/Rocket.Chat.Electron/releases))?
        4. Is there any setting relevant to the problem that changed?
      placeholder: A clear and concise description of what the bug is

    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce
      description: |
        Explain the steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem
        as minimally and precisely as possible
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your Expected behavior
      description: |
        - Please explain why you think the behaviour is erroneous.

        - It will be extremely helpful if you copy and paste
          screenshots for UI problems
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else
      description: |
        1. How often does this problem occur?
            - Once?
            - Every time?
            - Only when certain conditions are met?
        2. Any relevant logs to include?
            - Put them here inside fenced \``` \``` blocks
            - Or put them inside a collapsable details tag if it's too long, like so:
              - `<details><summary>x.log</summary> lots of stuff </details>`
      placeholder: Anything else we need to know?

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: |
        - We would be happy to guide you in the contribution process especially if you already have a good understanding of how to implement the fix.
        - Rocket.Chat.Electron is a community-driven project and we would love to bring new contributors in.
      options:
        - label: Yes, I am willing to submit a PR!

  - type: markdown
    attributes:
      value: 'Thank you for submitting your issue, we really appreciate it!'
