name: Feature request
description: Suggest an idea for this project
title: '[Feature][Module Name] Feature title'
labels: ['type/feature-request']
body:
  - type: markdown
    attributes:
      value: |
        For better global communication, please write in English.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) first
        to see whether the same feature was requested already.
      options:
        - label: >
            I have searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no
            similar feature requirement.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature

  - type: textarea
    attributes:
      label: Use case
      description: What do you want to happen?
      placeholder: >
        Explain what you are trying to achieve

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: |
        - We would be happy to guide you in the contribution process especially if you already have a good understanding of how to implement the fix.
        - Rocket.Chat.Electron is a community-driven project and we would love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: 'Thanks for completing our form!'
